### ISSUE TITLE
AttributeError: 'MediaUtility' object has no attribute 'configuration'

### ISSUE THREAD

**Issue by Senooy** [InstaPy2/InstaPy2#12]
After launching the script and successfully logged in, this returns me this error in Terminal 

`[INFO]: Successfully logged in as: falconmarketingfr.
Traceback (most recent call last):
  File "/Users/youneskhelifi/Documents/projets/insta/single_session.py", line 24, in <module>
    session.like(amount=10, iterable=['christmas'], type=LikeType.Tags)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/instapy2.py", line 232, in like
    medias = self.configuration.media.medias_tag(amount=amount, tag=tag, randomize_media=randomize_media, skip_top=skip_top)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/utilities/media.py", line 58, in medias_tag
    medias += [media for media in self.session.hashtag_medias_recent(name=tag, amount=amount) if not any(username in media.user.username for username in self.configuration.people.users_to_skip)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/utilities/media.py", line 58, in <listcomp>
    medias += [media for media in self.session.hashtag_medias_recent(name=tag, amount=amount) if not any(username in media.user.username for username in self.configuration.people.users_to_skip)]
                                                                                                                                                         ^^^^^^^^^^^^^^^^^^
AttributeError: 'MediaUtility' object has no attribute 'configuration'`

Am I doing anything wrong ?

**Comment by jarrodnorwell** [comment]
Should be fixed in #13
