### ISSUE TITLE
Error on likes on tag

### ISSUE THREAD

**Issue by Senooy** [InstaPy2/InstaPy2#15]
While using like_tags.py, the console returns me this

[INFO]: Successfully logged in as: ********
Traceback (most recent call last):
  File "/Users/youneskhelifi/Documents/projets/InstaPy2/like_tags.py", line 7, in <module>
    session.like(amount=10, iterable=['roubaix'], type=LikeType.Tags)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/instapy2.py", line 232, in like
    medias = self.configuration.media.medias_tag(amount=amount, tag=tag, randomize_media=randomize_media, skip_top=skip_top)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/utilities/media.py", line 58, in medias_tag
    medias += [media for media in self.session.hashtag_medias_recent(name=tag, amount=amount) if not any(username in media.user.username for username in self.configuration.people.users_to_skip)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/utilities/media.py", line 58, in <listcomp>
    medias += [media for media in self.session.hashtag_medias_recent(name=tag, amount=amount) if not any(username in media.user.username for username in self.configuration.people.users_to_skip)]
                                                                                                                                                         ^^^^^^^^^^^^^^^^^^
AttributeError: 'MediaUtility' object has no attribute 'configuration'

Did I do something wrong ?

**Comment by jarrodnorwell** [comment]
Are you using the GitHub or PyPI version? GitHub has the fix for this but PyPI does not yet.

**Comment by Senooy** [comment]
I downloaded the GitHub project, and changed the script for my logs, that's it

**Comment by jarrodnorwell** [comment]
Could you run `git clone https://github.com/InstaPy2/InstaPy2; cd InstaPy2; pip install .`? There should be no issue with the latest version.

**Comment by Senooy** [comment]
Now it returns me this : 

Traceback (most recent call last):
  File "/Users/youneskhelifi/InstaPy2/like_tags.py", line 1, in <module>
    from instapy2 import InstaPy2
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/__init__.py", line 1, in <module>
    from .instapy2 import InstaPy2
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/instapy2.py", line 1, in <module>
    from .instapy2_base import InstaPy2Base
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/instapy2_base.py", line 1, in <module>
    from .configuration import Configuration
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/configuration.py", line 4, in <module>
    from .utilities import CommentsUtility
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/utilities/__init__.py", line 1, in <module>
    from .comments import CommentsUtility
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/utilities/comments.py", line 1, in <module>
    from ..configuration import Configuration
ImportError: cannot import name 'Configuration' from partially initialized module 'instapy2.configuration' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instapy2/configuration.py)

**Comment by jarrodnorwell** [comment]
@Senooy should be fixed now if you do `git pull; pip install .`, for some reason the pull request didn't work.

**Comment by Senooy** [comment]
Everything works perfectly ! Do yo have any documentation available ? The link in GitHub is broken

**Comment by jarrodnorwell** [comment]
Only examples currently but I'll be adding documentation, just bad at writing it honestly.

**Comment by Senooy** [comment]
Is it possible to interact (like, follow, comment) with people following a page? If you need any help for documentation, I'm here 👋🏼

**Comment by jarrodnorwell** [comment]
@Senooy it is indeed, you can comment, like and follow media and users.
