### ISSUE TITLE
AttributeError MediaUtility

### ISSUE THREAD

**Issue by m-deane** [InstaPy2/InstaPy2#21]
When trying to use the like and comment example.py script I receive the following AttributeError: MediaUtility

Is there a MediaUtility class that needs to be set up or am I missing something?

Traceback (most recent call last):
  File "e:\Python_projects\Udemy\Web Automation Instagram in Python\InstaPy\unfollow_bot2.py", line 66, in <module>
    session.like(amount=53, iterable=hashtags, type=LikeType.Tags)
  File "C:\Users\user\miniconda3\lib\site-packages\instapy2\instapy2.py", line 232, in like
    medias = self.configuration.media.medias_tag(amount=amount, tag=tag, randomize_media=randomize_media, skip_top=skip_top)
  File "C:\Users\user\miniconda3\lib\site-packages\instapy2\utilities\media.py", line 58, in medias_tag
    medias += [media for media in self.session.hashtag_medias_recent(name=tag, amount=amount) if not any(username in media.user.username for username in self.configuration.people.users_to_skip)]
  File "C:\Users\user\miniconda3\lib\site-packages\instapy2\utilities\media.py", line 58, in <listcomp>
    medias += [media for media in self.session.hashtag_medias_recent(name=tag, amount=amount) if not any(username in media.user.username for username in self.configuration.people.users_to_skip)]
**AttributeError: 'MediaUtility' object has no attribute 'configuration'**

Thanks!

**Comment by jarrodnorwell** [comment]
Hey @m-deane,

The PyPI version is outdated currently while the rework is going on, you'll need to install the Git version: `git clone https://github.com/InstaPy2/InstaPy2; cd InstaPy2; pip install .`

**Comment by m-deane** [comment]
Thanks, all working :)
