### ISSUE TITLE
Issue when trying to like by hashtags

### ISSUE THREAD

**Issue by itsGarrin** [InstaPy2/InstaPy2#41]
Traceback (most recent call last):
  File "/Users/PycharmProjects/InstaPy/ivy.py", line 34, in <module>
    session.like.hashtags(amount=10, iterable=["mentalhealth"])
  File "/Users/PycharmProjects/InstaPy/venv12/lib/python3.12/site-packages/instapy2/utilities/like.py", line 34, in hashtags
    posts = hashtags_medias(name=hashtag, amount=amount)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PycharmProjects/InstaPy/venv12/lib/python3.12/site-packages/instagrapi/mixins/hashtag.py", line 444, in hashtag_medias_recent
    medias = self.hashtag_medias_recent_a1(name, amount)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PycharmProjects/InstaPy/venv12/lib/python3.12/site-packages/instagrapi/mixins/hashtag.py", line 407, in hashtag_medias_recent_a1
    return self.hashtag_medias_a1(name, amount, tab_key="recent")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PycharmProjects/InstaPy/venv12/lib/python3.12/site-packages/instagrapi/mixins/hashtag.py", line 222, in hashtag_medias_a1
    medias, _ = self.hashtag_medias_a1_chunk(name, amount, tab_key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PycharmProjects/InstaPy/venv12/lib/python3.12/site-packages/instagrapi/mixins/hashtag.py", line 195, in hashtag_medias_a1_chunk
    if not result["more_available"]:
           ~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'more_available'

Seems like an issue with the api calls. Let me know if you need more information. Thanks!

**Comment by jarrodnorwell** [comment]
Hey @itsGarrin, did you install InstaPy2 through GitHub or PyPI?

**Comment by itsGarrin** [comment]
I first tried through PyPi, then overwrote all the files in site packages via GitHub

**Comment by jarrodnorwell** [comment]
Looking at what you sent again it actually looks like an Instagrapi issue so I'll probably fix that for them assuming it's not done by the time I get to it

**Comment by itsGarrin** [comment]
Perfect! Let me know when you get to it.

**Comment by jarrodnorwell** [comment]
@itsGarrin fixed locally, will do a PR for them and see what they think

**Comment by jarrodnorwell** [comment]
@itsGarrin they've merged my PR with the fix, if you update Instagrapi from GitHub (or maybe PyPI) it should fix those issues: `pip install git+https://github.com/subzeroid/instagrapi`

**Comment by itsGarrin** [comment]
Perfect! Tysm for the help man
